### ISSUE TITLE
Can't browse/search pages

### ISSUE THREAD

**Issue by manuelmeister** [intoxstudio/restrict-user-access#1]
![page](https://cloud.githubusercontent.com/assets/3001985/6937333/4247c546-d85b-11e4-870a-2c24e3705d93.gif)

Wordpress 4.1.1

**Comment by intoxstudio** [comment]
Thanks for the heads up! This has been fixed. For now you can download a zipball from github, but it will be updated on the wordpress repository soon too.

**Comment by manuelmeister** [comment]
Thank you very much! :) It works now.
