### ISSUE TITLE
show_admin_bar on / off always for all roles

### ISSUE THREAD

**Issue by infosion** [intoxstudio/restrict-user-access#10]
I am trying to hide the admin bar for specific roles:
`if ( ! current_user_can( 'manage_options' ) ) {
    show_admin_bar( false );
}`
Unfortunately this is not working with restrict user access plugin activated. 
Also general deactivating is not working:
`add_filter('show_admin_bar', '__return_false');` or
`show_admin_bar( false );`
Any tip would be great! Thanks much.

**Comment by intoxstudio** [comment]
Restrict User Access hooks into show_admin_bar at priority 99, so try this instead:

`add_filter('show_admin_bar', '__return_false', 100);`

**Comment by infosion** [comment]
Thanks! That solved everything.
