### ISSUE TITLE
How to Determine the level required for a page

### ISSUE THREAD

**Issue by wturnerharris** [intoxstudio/restrict-user-access#19]
Define public API method to deduce the Access Level of a given piece of content. 

--

We would used this to check if a page is protected so that the user does not have to be redirected to login.

**Comment by intoxstudio** [comment]
Would it be sufficient with a method like `user_has_access():boolean`?

Can you tell me more about the use case, e.g. why would you not use the built-in redirect/tease functionality on restricted content?

**Comment by wturnerharris** [comment]
@intoxstudio - thanks for getting back.

Sometimes we need to know something about a page (and it's access level) before outputting its link or content. This needs to be separate from a user's access level.

```php
global $post;

if ( empty( get_post_meta( $post->ID, "access_level", true ) ) {
// ...
}
```

In our particular case, we want to filter all links so that the direct link to protected content is never exposed. By this same logic, we can change the URL, say, to the login url with the redirect url query string.

**Comment by intoxstudio** [comment]
Thanks for the clarification! Due to the way the restrictions/conditions are stored, it is currently not always feasable to get that info about a particular post/page. It is something I am working on, and this functionality would also allow automatically hiding/filtering restricted content from archives, lists, widgets etc.

If you restrict posts/pages individually (not by category, author, etc.) then you might be able to leverage something like this for now:

```
global $wpdb, $post;

//get levels current user doesnt have
$other_levels = array_diff(
	array_keys(RUA_App::instance()->get_levels()),
	rua_get_user_levels()
);

//get posts/page IDS that current user does not have access to
$post_ids = array_flip($wpdb->get_col("SELECT m.meta_value FROM $wpdb->postmeta m INNER JOIN $wpdb->posts p ON m.post_id = p.ID WHERE m.meta_key = '_ca_post_type' AND p.post_parent IN ('".implode("','", $other_levels)."')"));

if ( !isset($post_ids[$post->ID])) {
    //display link
}
```

**Comment by Sanabria** [comment]
I have a similar problem: Is there a workaround to prevent protected terms from appearing to a user without access when looping through get_terms or get_categories?
