### ISSUE TITLE
Can't bulk remove members from access level

### ISSUE THREAD

**Issue by theninabird** [intoxstudio/restrict-user-access#28]
**Description**
When I select multiple users on the Edit Access Level < Members tab, then select Remove from the Bulk actions menu and apply, nothing happens. All of the members were added via a User Role automation trigger.

**To Reproduce**
1. Go to User Access < Access Levels and select Access Level
2. Click Members tab
3. Select multiple Members by clicking the checkboxes or Select All
4. In Bulk Actions menu, choose Remove
5. Click Apply

**Expected behavior**
The selected members will be removed from the access level.

**Screenshots**
Video recording of issue: https://www.loom.com/share/2596f900e723434d9800453e8e4d030b

**Comment by theninabird** [comment]
Also, this is more of a feature request, but it would be awesome if user access that was added by an automation trigger of user role could be automatically removed when the user loses that role.

**Comment by intoxstudio** [comment]
Thank you for reporting this, it will be fixed in https://github.com/intoxstudio/restrict-user-access/pull/30

I have noted down your feature request as well, for now you can use the Sync option, so the level always follows the role

**Comment by theninabird** [comment]
Oh duh, I didn't even think to use the Sync option! That will solve my problem. Thank you for responding!
