### ISSUE TITLE
Multiple Access to restricted section

### ISSUE THREAD

**Issue by jakekimpton** [intoxstudio/restrict-user-access#3]
Hi,

I want to be able to give restricted access to 2 user groups like the code below, is this possible? One can not inherit anothers' roles using Extend because they have very different permissions. 

```
[restrict role="usergroup1, usergroup2"]

Some restricted content only ug1 and ug2 should see

[/restrict]
```

**Comment by intoxstudio** [comment]
The restrict shortcode can be used to target both roles and levels. I assume you want to target multiple levels (that do not extend each other)?

It is currently possible to target multiple roles like in your example (but without the space "usergroup1,usergroup2").

**Comment by jakekimpton** [comment]
Perfect! Thanks for the help
