### ISSUE TITLE
Restrict visibility of BuddyPress pages to a user's BuddyPress friends?

### ISSUE THREAD

**Issue by adambreen** [intoxstudio/restrict-user-access#4]
Hey there,

I'm hoping restrict-user-access can really help us avoid writing code!

We are building a Wordpress Multisite network, with BuddyPress network-activated (thus its toolbar is visible on all sites in the network).

However, we want to ensure similar privacy levels to Facebook, in the sense that our users' BuddyPress profiles should be (able to be) private, except to other users who they have a BuddyPress relationship with (eg. followers).

So there are two key use cases:
1. Public internet (not logged in to BuddyPress): do not show any BuddyPress member profile details, especially their Sites page (ie. the old "blogs" page).
2. Logged-in user: only show BuddyPress "Sites" page and "Activity" to other users who are logged-in and, say, following the profile in question.

Please let me know if Restrict User Access can achieve the above?  I apologise for using a GitHub issue to ask this question — I couldn't find a better way to contact you!

Warm regards,

Adam

**Comment by intoxstudio** [comment]
Sorry for the delayed response here.

Some of the functionality you are describing is not built into the plugin, but it is possible to restrict access to specific BuddyPress pages to users that are not logged in (Use case 1).
Hiding parts of a page can be done with a shortcode or by using rua_has_user_level($user_id:int,$level_id:int) in the theme templates.

I think BuddyPress already has built-in functionality to hide profile posts/statuses to friends/followers, so I would recommend you look into expanding that for use case 2. At this point, I think it would be too much work to try to implement that use case with this plugin, but if you plan on doing it, I would be more than happy to answer any questions and see the result.
