### ISSUE TITLE
WPCAObjectManager not found

### ISSUE THREAD

**Issue by sitmo** [intoxstudio/restrict-user-access#6]
Hi, I'm getting the following fatal error in my log files and the WP site doesn't render. Any idea what might be causing it?

> Class 'WPCAObjectManager' not found in /var/.../wordpress/wp-content/plugins/restrict-user-access/level.php on line 228

**Comment by intoxstudio** [comment]
This has been reported here too (along with a temporary fix): https://wordpress.org/support/topic/error-after-login-3/

Does your log file by any change contain the stack trace to the error? I am currently investigating what is causing the error, but have not been able to reproduce it yet.
