### ISSUE TITLE
Use RUA SVG icon in WP backend

### ISSUE THREAD

**Issue by JoryHogeveen** [intoxstudio/restrict-user-access#9]
Why not make a SVG icon to use in WP admin instead of the current dashicon?
If you would like help on this, please send me the vector/original file!
![restrict-user-access](https://cloud.githubusercontent.com/assets/826148/21258063/9e9fb5da-c37b-11e6-8985-c5d9bb5e466f.png)

**Comment by intoxstudio** [comment]
This is a good idea. Tried to add an SVG of this icon, but it doesn't look very good at 20x20 pixels, so I might have to alter it for the menu.

**Comment by JoryHogeveen** [comment]
Let me know if you need any help with this!
You can also consider to use `dashicons-admin-network` for this like I did for the VAA module. Or maybe modify it a bit.

**Comment by JoryHogeveen** [comment]
Icon idea for WP Admin:
![rua](https://user-images.githubusercontent.com/826148/31279459-6f04c2d2-aaa9-11e7-972b-0e9938d6c6ab.png)

**Comment by intoxstudio** [comment]
Thanks for this! I am considering changing the logo entirely and not rely on dashicons, just so I have a unified brand for the plugin.

Are SVG formats available for all dashicons, or did you use a tool to extract it from the font?

**Comment by JoryHogeveen** [comment]
Ah okidoki!
SVG formats can be found on the GitHub repo: https://github.com/WordPress/dashicons/tree/master/sources/svg

**Comment by JoryHogeveen** [comment]
Compliments on the new icon! Nice

**Comment by JoryHogeveen** [comment]
@intoxstudio 
Hey Joachim,
Keep in mind that your current solution (SVG icon) doesn't support hover colors. If you convert it to an icon font it will :)
